// Copyright (c) 2013 Tony Wilson. All rights reserved.
// See LICENCE file for permissions and restrictions.

//Package opengl provides API definitions for accessing
//opengl32.dll.
package opengl

import "github.com/tHinqa/outside"

func init() {
	outside.AddDllApis("opengl32.dll", false, allApis)
}

var allApis = outside.Apis{
	// "GlmfBeginGlsBlock",
	// "GlmfCloseMetaFile",
	// "GlmfEndGlsBlock",
	// "GlmfEndPlayback",
	// "GlmfInitPlayback",
	// "GlmfPlayGlsRecord",
	{"glAccum", &Accum},
	// {"glActiveProgramEXT", &ActiveProgramEXT},
	// {"glActiveTexture", &ActiveTexture},
	// {"glActiveTextureARB", &ActiveTextureARB},
	// {"glAlphaFragmentOp1ATI", &AlphaFragmentOp1ATI},
	// {"glAlphaFragmentOp2ATI", &AlphaFragmentOp2ATI},
	// {"glAlphaFragmentOp3ATI", &AlphaFragmentOp3ATI},
	{"glAlphaFunc", &AlphaFunc},
	// {"glAreProgramsResidentNV", &AreProgramsResidentNV},
	{"glAreTexturesResident", &AreTexturesResident},
	// {"glAreTexturesResidentEXT", &AreTexturesResidentEXT},
	{"glArrayElement", &ArrayElement},
	// {"glArrayElementEXT", &ArrayElementEXT},
	// {"glAttachObjectARB", &AttachObjectARB},
	// {"glAttachShader", &AttachShader},
	{"glBegin", &Begin},
	// {"glBeginConditionalRender", &BeginConditionalRender},
	// {"glBeginConditionalRenderNV", &BeginConditionalRenderNV},
	// {"glBeginFragmentShaderATI", &BeginFragmentShaderATI},
	// {"glBeginQuery", &BeginQuery},
	// {"glBeginQueryARB", &BeginQueryARB},
	// {"glBeginTransformFeedback", &BeginTransformFeedback},
	// {"glBeginTransformFeedbackEXT", &BeginTransformFeedbackEXT},
	// {"glBindAttribLocation", &BindAttribLocation},
	// {"glBindAttribLocationARB", &BindAttribLocationARB},
	// {"glBindBuffer", &BindBuffer},
	// {"glBindBufferARB", &BindBufferARB},
	// {"glBindBufferBase", &BindBufferBase},
	// {"glBindBufferBaseEXT", &BindBufferBaseEXT},
	// {"glBindBufferOffsetEXT", &BindBufferOffsetEXT},
	// {"glBindBufferRange", &BindBufferRange},
	// {"glBindBufferRangeEXT", &BindBufferRangeEXT},
	// {"glBindFragDataLocation", &BindFragDataLocation},
	// {"glBindFragDataLocationEXT", &BindFragDataLocationEXT},
	// {"glBindFragmentShaderATI", &BindFragmentShaderATI},
	// {"glBindFramebuffer", &BindFramebuffer},
	// {"glBindFramebufferEXT", &BindFramebufferEXT},
	// {"glBindProgramARB", &BindProgramARB},
	// {"glBindProgramNV", &BindProgramNV},
	// {"glBindRenderbuffer", &BindRenderbuffer},
	// {"glBindRenderbufferEXT", &BindRenderbufferEXT},
	// {"glBindSampler", &BindSampler},
	{"glBindTexture", &BindTexture},
	// {"glBindTextureEXT", &BindTextureEXT},
	// {"glBindTransformFeedback", &BindTransformFeedback},
	// {"glBindVertexArray", &BindVertexArray},
	{"glBitmap", &Bitmap},
	// {"glBlendColor", &BlendColor},
	// {"glBlendColorEXT", &BlendColorEXT},
	// {"glBlendEquation", &BlendEquation},
	// {"glBlendEquationEXT", &BlendEquationEXT},
	// {"glBlendEquationiARB", &BlendEquationiARB},
	// {"glBlendEquationIndexedAMD", &BlendEquationIndexedAMD},
	// {"glBlendEquationSeparate", &BlendEquationSeparate},
	// {"glBlendEquationSeparateiARB", &BlendEquationSeparateiARB},
	// {"glBlendEquationSeparateIndexedAMD", &BlendEquationSeparateIndexedAMD},
	{"glBlendFunc", &BlendFunc},
	// {"glBlendFunciARB", &BlendFunciARB},
	// {"glBlendFuncIndexedAMD", &BlendFuncIndexedAMD},
	// {"glBlendFuncSeparate", &BlendFuncSeparate},
	// {"glBlendFuncSeparateEXT", &BlendFuncSeparateEXT},
	// {"glBlendFuncSeparateiARB", &BlendFuncSeparateiARB},
	// {"glBlendFuncSeparateIndexedAMD", &BlendFuncSeparateIndexedAMD},
	// {"glBlitFramebuffer", &BlitFramebuffer},
	// {"glBufferData", &BufferData},
	// {"glBufferDataARB", &BufferDataARB},
	// {"glBufferSubData", &BufferSubData},
	// {"glBufferSubDataARB", &BufferSubDataARB},
	{"glCallList", &CallList},
	{"glCallLists", &CallLists},
	// {"glCheckFramebufferStatus", &CheckFramebufferStatus},
	// {"glCheckFramebufferStatusEXT", &CheckFramebufferStatusEXT},
	// {"glClampColor", &ClampColor},
	// {"glClampColorARB", &ClampColorARB},
	{"glClear", &Clear},
	{"glClearAccum", &ClearAccum},
	// {"glClearBufferfi", &ClearBufferfi},
	// {"glClearBufferfv", &ClearBufferfv},
	// {"glClearBufferiv", &ClearBufferiv},
	// {"glClearBufferuiv", &ClearBufferuiv},
	{"glClearColor", &ClearColor},
	// {"glClearColorIiEXT", &ClearColorIiEXT},
	// {"glClearColorIuiEXT", &ClearColorIuiEXT},
	{"glClearDepth", &ClearDepth},
	// {"glClearDepthf", &ClearDepthf},
	{"glClearIndex", &ClearIndex},
	{"glClearStencil", &ClearStencil},
	// {"glClientActiveTexture", &ClientActiveTexture},
	// {"glClientActiveTextureARB", &ClientActiveTextureARB},
	// {"glClientWaitSync", &ClientWaitSync},
	{"glClipPlane", &ClipPlane},
	{"glColor3b", &Color3b},
	{"glColor3bv", &Color3bv},
	{"glColor3d", &Color3d},
	{"glColor3dv", &Color3dv},
	{"glColor3f", &Color3f},
	{"glColor3fv", &Color3fv},
	{"glColor3i", &Color3i},
	{"glColor3iv", &Color3iv},
	{"glColor3s", &Color3s},
	{"glColor3sv", &Color3sv},
	{"glColor3ub", &Color3ub},
	{"glColor3ubv", &Color3ubv},
	{"glColor3ui", &Color3ui},
	{"glColor3uiv", &Color3uiv},
	{"glColor3us", &Color3us},
	{"glColor3usv", &Color3usv},
	{"glColor4b", &Color4b},
	{"glColor4bv", &Color4bv},
	{"glColor4d", &Color4d},
	{"glColor4dv", &Color4dv},
	{"glColor4f", &Color4f},
	{"glColor4fv", &Color4fv},
	{"glColor4i", &Color4i},
	{"glColor4iv", &Color4iv},
	{"glColor4s", &Color4s},
	{"glColor4sv", &Color4sv},
	{"glColor4ub", &Color4ub},
	{"glColor4ubv", &Color4ubv},
	{"glColor4ui", &Color4ui},
	{"glColor4uiv", &Color4uiv},
	{"glColor4us", &Color4us},
	{"glColor4usv", &Color4usv},
	// {"glColorFragmentOp1ATI", &ColorFragmentOp1ATI},
	// {"glColorFragmentOp2ATI", &ColorFragmentOp2ATI},
	// {"glColorFragmentOp3ATI", &ColorFragmentOp3ATI},
	{"glColorMask", &ColorMask},
	// {"glColorMaski", &ColorMaski},
	// {"glColorMaskIndexedEXT", &ColorMaskIndexedEXT},
	{"glColorMaterial", &ColorMaterial},
	// {"glColorP3ui", &ColorP3ui},
	// {"glColorP3uiv", &ColorP3uiv},
	// {"glColorP4ui", &ColorP4ui},
	// {"glColorP4uiv", &ColorP4uiv},
	{"glColorPointer", &ColorPointer},
	// {"glColorPointerEXT", &ColorPointerEXT},
	// {"glColorSubTable", &ColorSubTable},
	// {"glColorTable", &ColorTable},
	// {"glColorTableEXT", &ColorTableEXT},
	// {"glColorTableParameterfv", &ColorTableParameterfv},
	// {"glColorTableParameteriv", &ColorTableParameteriv},
	// {"glCombinerInputNV", &CombinerInputNV},
	// {"glCombinerOutputNV", &CombinerOutputNV},
	// {"glCombinerParameterfNV", &CombinerParameterfNV},
	// {"glCombinerParameterfvNV", &CombinerParameterfvNV},
	// {"glCombinerParameteriNV", &CombinerParameteriNV},
	// {"glCombinerParameterivNV", &CombinerParameterivNV},
	// {"glCompileShader", &CompileShader},
	// {"glCompileShaderARB", &CompileShaderARB},
	// {"glCompressedTexImage1D", &CompressedTexImage1D},
	// {"glCompressedTexImage1DARB", &CompressedTexImage1DARB},
	// {"glCompressedTexImage2D", &CompressedTexImage2D},
	// {"glCompressedTexImage2DARB", &CompressedTexImage2DARB},
	// {"glCompressedTexImage3D", &CompressedTexImage3D},
	// {"glCompressedTexImage3DARB", &CompressedTexImage3DARB},
	// {"glCompressedTexSubImage1D", &CompressedTexSubImage1D},
	// {"glCompressedTexSubImage1DARB", &CompressedTexSubImage1DARB},
	// {"glCompressedTexSubImage2D", &CompressedTexSubImage2D},
	// {"glCompressedTexSubImage2DARB", &CompressedTexSubImage2DARB},
	// {"glCompressedTexSubImage3D", &CompressedTexSubImage3D},
	// {"glCompressedTexSubImage3DARB", &CompressedTexSubImage3DARB},
	// {"glConvolutionFilter1D", &ConvolutionFilter1D},
	// {"glConvolutionFilter2D", &ConvolutionFilter2D},
	// {"glConvolutionParameterf", &ConvolutionParameterf},
	// {"glConvolutionParameterfv", &ConvolutionParameterfv},
	// {"glConvolutionParameteri", &ConvolutionParameteri},
	// {"glConvolutionParameteriv", &ConvolutionParameteriv},
	// {"glCopyBufferSubData", &CopyBufferSubData},
	// {"glCopyColorSubTable", &CopyColorSubTable},
	// {"glCopyColorTable", &CopyColorTable},
	// {"glCopyConvolutionFilter1D", &CopyConvolutionFilter1D},
	// {"glCopyConvolutionFilter2D", &CopyConvolutionFilter2D},
	{"glCopyPixels", &CopyPixels},
	{"glCopyTexImage1D", &CopyTexImage1D},
	// {"glCopyTexImage1DEXT", &CopyTexImage1DEXT},
	{"glCopyTexImage2D", &CopyTexImage2D},
	// {"glCopyTexImage2DEXT", &CopyTexImage2DEXT},
	{"glCopyTexSubImage1D", &CopyTexSubImage1D},
	// {"glCopyTexSubImage1DEXT", &CopyTexSubImage1DEXT},
	{"glCopyTexSubImage2D", &CopyTexSubImage2D},
	// {"glCopyTexSubImage2DEXT", &CopyTexSubImage2DEXT},
	// {"glCopyTexSubImage3D", &CopyTexSubImage3D},
	// {"glCopyTexSubImage3DEXT", &CopyTexSubImage3DEXT},
	// {"glCreateProgram", &CreateProgram},
	// {"glCreateProgramObjectARB", &CreateProgramObjectARB},
	// {"glCreateShader", &CreateShader},
	// {"glCreateShaderObjectARB", &CreateShaderObjectARB},
	// {"glCreateShaderProgramEXT", &CreateShaderProgramEXT},
	{"glCullFace", &CullFace},
	// "glDebugEntry",
	// {"glDeleteBuffers", &DeleteBuffers},
	// {"glDeleteBuffersARB", &DeleteBuffersARB},
	// {"glDeleteFragmentShaderATI", &DeleteFragmentShaderATI},
	// {"glDeleteFramebuffers", &DeleteFramebuffers},
	// {"glDeleteFramebuffersEXT", &DeleteFramebuffersEXT},
	{"glDeleteLists", &DeleteLists},
	// {"glDeleteObjectARB", &DeleteObjectARB},
	// {"glDeleteProgram", &DeleteProgram},
	// {"glDeleteProgramsARB", &DeleteProgramsARB},
	// {"glDeleteProgramsNV", &DeleteProgramsNV},
	// {"glDeleteQueries", &DeleteQueries},
	// {"glDeleteQueriesARB", &DeleteQueriesARB},
	// {"glDeleteRenderbuffers", &DeleteRenderbuffers},
	// {"glDeleteRenderbuffersEXT", &DeleteRenderbuffersEXT},
	// {"glDeleteSamplers", &DeleteSamplers},
	// {"glDeleteShader", &DeleteShader},
	// {"glDeleteSync", &DeleteSync},
	{"glDeleteTextures", &DeleteTextures},
	// {"glDeleteTexturesEXT", &DeleteTexturesEXT},
	// {"glDeleteTransformFeedbacks", &DeleteTransformFeedbacks},
	// {"glDeleteVertexArrays", &DeleteVertexArrays},
	{"glDepthFunc", &DepthFunc},
	{"glDepthMask", &DepthMask},
	{"glDepthRange", &DepthRange},
	// {"glDepthRangef", &DepthRangef},
	// {"glDetachObjectARB", &DetachObjectARB},
	// {"glDetachShader", &DetachShader},
	// {"glDisable", &Disable},
	{"glDisableClientState", &DisableClientState},
	// {"glDisablei", &Disablei},
	// {"glDisableIndexedEXT", &DisableIndexedEXT},
	// {"glDisableVertexAttribArray", &DisableVertexAttribArray},
	// {"glDisableVertexAttribArrayARB", &DisableVertexAttribArrayARB},
	{"glDrawArrays", &DrawArrays},
	// {"glDrawArraysEXT", &DrawArraysEXT},
	// {"glDrawArraysInstanced", &DrawArraysInstanced},
	// {"glDrawArraysInstancedARB", &DrawArraysInstancedARB},
	// {"glDrawArraysInstancedEXT", &DrawArraysInstancedEXT},
	{"glDrawBuffer", &DrawBuffer},
	// {"glDrawBuffers", &DrawBuffers},
	// {"glDrawBuffersARB", &DrawBuffersARB},
	// {"glDrawBuffersATI", &DrawBuffersATI},
	// {"glDrawBuffersNV", &DrawBuffersNV},
	{"glDrawElements", &DrawElements},
	// {"glDrawElementsBaseVertex", &DrawElementsBaseVertex},
	// {"glDrawElementsInstanced", &DrawElementsInstanced},
	// {"glDrawElementsInstancedARB", &DrawElementsInstancedARB},
	// {"glDrawElementsInstancedBaseVertex", &DrawElementsInstancedBaseVertex},
	// {"glDrawElementsInstancedEXT", &DrawElementsInstancedEXT},
	{"glDrawPixels", &DrawPixels},
	// {"glDrawRangeElements", &DrawRangeElements},
	// {"glDrawRangeElementsBaseVertex", &DrawRangeElementsBaseVertex},
	// {"glDrawRangeElementsEXT", &DrawRangeElementsEXT},
	// {"glDrawTransformFeedback", &DrawTransformFeedback},
	{"glEdgeFlag", &EdgeFlag},
	{"glEdgeFlagPointer", &EdgeFlagPointer},
	// {"glEdgeFlagPointerEXT", &EdgeFlagPointerEXT},
	{"glEdgeFlagv", &EdgeFlagv},
	// {"glEGLImageTargetRenderbufferStorageOES", &EGLImageTargetRenderbufferStorageOES},
	// {"glEGLImageTargetTexture2DOES", &EGLImageTargetTexture2DOES},
	{"glEnable", &Enable},
	{"glEnableClientState", &EnableClientState},
	// {"glEnablei", &Enablei},
	// {"glEnableIndexedEXT", &EnableIndexedEXT},
	// {"glEnableVertexAttribArray", &EnableVertexAttribArray},
	// {"glEnableVertexAttribArrayARB", &EnableVertexAttribArrayARB},
	{"glEnd", &End},
	// {"glEndConditionalRender", &EndConditionalRender},
	// {"glEndConditionalRenderNV", &EndConditionalRenderNV},
	// {"glEndFragmentShaderATI", &EndFragmentShaderATI},
	{"glEndList", &EndList},
	// {"glEndQuery", &EndQuery},
	// {"glEndQueryARB", &EndQueryARB},
	// {"glEndTransformFeedback", &EndTransformFeedback},
	// {"glEndTransformFeedbackEXT", &EndTransformFeedbackEXT},
	{"glEvalCoord1d", &EvalCoord1d},
	{"glEvalCoord1dv", &EvalCoord1dv},
	{"glEvalCoord1f", &EvalCoord1f},
	{"glEvalCoord1fv", &EvalCoord1fv},
	{"glEvalCoord2d", &EvalCoord2d},
	{"glEvalCoord2dv", &EvalCoord2dv},
	{"glEvalCoord2f", &EvalCoord2f},
	{"glEvalCoord2fv", &EvalCoord2fv},
	{"glEvalMesh1", &EvalMesh1},
	{"glEvalMesh2", &EvalMesh2},
	{"glEvalPoint1", &EvalPoint1},
	{"glEvalPoint2", &EvalPoint2},
	// {"glExecuteProgramNV", &ExecuteProgramNV},
	{"glFeedbackBuffer", &FeedbackBuffer},
	// {"glFenceSync", &FenceSync},
	// {"glFinalCombinerInputNV", &FinalCombinerInputNV},
	{"glFinish", &Finish},
	{"glFlush", &Flush},
	// {"glFlushMappedBufferRange", &FlushMappedBufferRange},
	// {"glFlushVertexArrayRangeNV", &FlushVertexArrayRangeNV},
	// {"glFogCoordd", &FogCoordd},
	// {"glFogCoorddEXT", &FogCoorddEXT},
	// {"glFogCoorddv", &FogCoorddv},
	// {"glFogCoorddvEXT", &FogCoorddvEXT},
	// {"glFogCoordf", &FogCoordf},
	// {"glFogCoordfEXT", &FogCoordfEXT},
	// {"glFogCoordfv", &FogCoordfv},
	// {"glFogCoordfvEXT", &FogCoordfvEXT},
	// {"glFogCoordPointer", &FogCoordPointer},
	// {"glFogCoordPointerEXT", &FogCoordPointerEXT},
	{"glFogf", &Fogf},
	{"glFogfv", &Fogfv},
	{"glFogi", &Fogi},
	{"glFogiv", &Fogiv},
	// {"glFramebufferRenderbuffer", &FramebufferRenderbuffer},
	// {"glFramebufferRenderbufferEXT", &FramebufferRenderbufferEXT},
	// {"glFramebufferTexture", &FramebufferTexture},
	// {"glFramebufferTexture1D", &FramebufferTexture1D},
	// {"glFramebufferTexture1DEXT", &FramebufferTexture1DEXT},
	// {"glFramebufferTexture2D", &FramebufferTexture2D},
	// {"glFramebufferTexture2DEXT", &FramebufferTexture2DEXT},
	// {"glFramebufferTexture3D", &FramebufferTexture3D},
	// {"glFramebufferTexture3DEXT", &FramebufferTexture3DEXT},
	// {"glFramebufferTextureARB", &FramebufferTextureARB},
	// {"glFramebufferTextureFaceARB", &FramebufferTextureFaceARB},
	// {"glFramebufferTextureLayer", &FramebufferTextureLayer},
	// {"glFramebufferTextureLayerARB", &FramebufferTextureLayerARB},
	// {"glFramebufferTextureLayerEXT", &FramebufferTextureLayerEXT},
	{"glFrontFace", &FrontFace},
	{"glFrustum", &Frustum},
	// {"glGenBuffers", &GenBuffers},
	// {"glGenBuffersARB", &GenBuffersARB},
	// {"glGenerateMipmap", &GenerateMipmap},
	// {"glGenerateMipmapEXT", &GenerateMipmapEXT},
	// {"glGenFragmentShadersATI", &GenFragmentShadersATI},
	// {"glGenFramebuffers", &GenFramebuffers},
	// {"glGenFramebuffersEXT", &GenFramebuffersEXT},
	{"glGenLists", &GenLists},
	// {"glGenProgramsARB", &GenProgramsARB},
	// {"glGenProgramsNV", &GenProgramsNV},
	// {"glGenQueries", &GenQueries},
	// {"glGenQueriesARB", &GenQueriesARB},
	// {"glGenRenderbuffers", &GenRenderbuffers},
	// {"glGenRenderbuffersEXT", &GenRenderbuffersEXT},
	// {"glGenSamplers", &GenSamplers},
	{"glGenTextures", &GenTextures},
	// {"glGenTexturesEXT", &GenTexturesEXT},
	// {"glGenTransformFeedbacks", &GenTransformFeedbacks},
	// {"glGenVertexArrays", &GenVertexArrays},
	// {"glGetActiveAttrib", &GetActiveAttrib},
	// {"glGetActiveAttribARB", &GetActiveAttribARB},
	// {"glGetActiveUniform", &GetActiveUniform},
	// {"glGetActiveUniformARB", &GetActiveUniformARB},
	// {"glGetAttachedObjectsARB", &GetAttachedObjectsARB},
	// {"glGetAttachedShaders", &GetAttachedShaders},
	// {"glGetAttribLocation", &GetAttribLocation},
	// {"glGetAttribLocationARB", &GetAttribLocationARB},
	// {"glGetBooleani_v", &GetBooleani_v},
	// {"glGetBooleanIndexedvEXT", &GetBooleanIndexedvEXT},
	{"glGetBooleanv", &GetBooleanv},
	// {"glGetBufferParameteri64v", &GetBufferParameteri64v},
	// {"glGetBufferParameteriv", &GetBufferParameteriv},
	// {"glGetBufferParameterivARB", &GetBufferParameterivARB},
	// {"glGetBufferPointerv", &GetBufferPointerv},
	// {"glGetBufferPointervARB", &GetBufferPointervARB},
	// {"glGetBufferSubData", &GetBufferSubData},
	// {"glGetBufferSubDataARB", &GetBufferSubDataARB},
	// {"glGetClipPlane", &GetClipPlane},
	// {"glGetColorTable", &GetColorTable},
	// {"glGetColorTableEXT", &GetColorTableEXT},
	// {"glGetColorTableParameterfv", &GetColorTableParameterfv},
	// {"glGetColorTableParameterfvEXT", &GetColorTableParameterfvEXT},
	// {"glGetColorTableParameteriv", &GetColorTableParameteriv},
	// {"glGetColorTableParameterivEXT", &GetColorTableParameterivEXT},
	// {"glGetCombinerInputParameterfvNV", &GetCombinerInputParameterfvNV},
	// {"glGetCombinerInputParameterivNV", &GetCombinerInputParameterivNV},
	// {"glGetCombinerOutputParameterfvNV", &GetCombinerOutputParameterfvNV},
	// {"glGetCombinerOutputParameterivNV", &GetCombinerOutputParameterivNV},
	// {"glGetCompressedTexImage", &GetCompressedTexImage},
	// {"glGetCompressedTexImageARB", &GetCompressedTexImageARB},
	// {"glGetConvolutionFilter", &GetConvolutionFilter},
	// {"glGetConvolutionParameterfv", &GetConvolutionParameterfv},
	// {"glGetConvolutionParameteriv", &GetConvolutionParameteriv},
	{"glGetDoublev", &GetDoublev},
	{"glGetError", &GetError},
	// {"glGetFinalCombinerInputParameterfvNV", &GetFinalCombinerInputParameterfvNV},
	// {"glGetFinalCombinerInputParameterivNV", &GetFinalCombinerInputParameterivNV},
	{"glGetFloatv", &GetFloatv},
	// {"glGetFragDataLocation", &GetFragDataLocation},
	// {"glGetFragDataLocationEXT", &GetFragDataLocationEXT},
	// {"glGetFramebufferAttachmentParameteriv", &GetFramebufferAttachmentParameteriv},
	// {"glGetFramebufferAttachmentParameterivEXT", &GetFramebufferAttachmentParameterivEXT},
	// {"glGetGraphicsResetStatusARB", &GetGraphicsResetStatusARB},
	// {"glGetHandleARB", &GetHandleARB},
	// {"glGetHistogram", &GetHistogram},
	// {"glGetHistogramParameterfv", &GetHistogramParameterfv},
	// {"glGetHistogramParameteriv", &GetHistogramParameteriv},
	// {"glGetInfoLogARB", &GetInfoLogARB},
	// {"glGetInteger64i_v", &GetInteger64i_v},
	// {"glGetInteger64v", &GetInteger64v},
	// {"glGetIntegeri_v", &GetIntegeri_v},
	// {"glGetIntegerIndexedvEXT", &GetIntegerIndexedvEXT},
	{"glGetIntegerv", &GetIntegerv},
	{"glGetLightfv", &GetLightfv},
	{"glGetLightiv", &GetLightiv},
	{"glGetMapdv", &GetMapdv},
	{"glGetMapfv", &GetMapfv},
	{"glGetMapiv", &GetMapiv},
	{"glGetMaterialfv", &GetMaterialfv},
	{"glGetMaterialiv", &GetMaterialiv},
	// {"glGetMinmax", &GetMinmax},
	// {"glGetMinmaxParameterfv", &GetMinmaxParameterfv},
	// {"glGetMinmaxParameteriv", &GetMinmaxParameteriv},
	// {"glGetnColorTableARB", &GetnColorTableARB},
	// {"glGetnCompressedTexImageARB", &GetnCompressedTexImageARB},
	// {"glGetnConvolutionFilterARB", &GetnConvolutionFilterARB},
	// {"glGetnHistogramARB", &GetnHistogramARB},
	// {"glGetnMapdvARB", &GetnMapdvARB},
	// {"glGetnMapfvARB", &GetnMapfvARB},
	// {"glGetnMapivARB", &GetnMapivARB},
	// {"glGetnMinmaxARB", &GetnMinmaxARB},
	// {"glGetnPixelMapfvARB", &GetnPixelMapfvARB},
	// {"glGetnPixelMapuivARB", &GetnPixelMapuivARB},
	// {"glGetnPixelMapusvARB", &GetnPixelMapusvARB},
	// {"glGetnPolygonStippleARB", &GetnPolygonStippleARB},
	// {"glGetnSeparableFilterARB", &GetnSeparableFilterARB},
	// {"glGetnTexImageARB", &GetnTexImageARB},
	// {"glGetnUniformdvARB", &GetnUniformdvARB},
	// {"glGetnUniformfvARB", &GetnUniformfvARB},
	// {"glGetnUniformivARB", &GetnUniformivARB},
	// {"glGetnUniformuivARB", &GetnUniformuivARB},
	// {"glGetObjectParameterfvARB", &GetObjectParameterfvARB},
	// {"glGetObjectParameterivAPPLE", &GetObjectParameterivAPPLE},
	// {"glGetObjectParameterivARB", &GetObjectParameterivARB},
	{"glGetPixelMapfv", &GetPixelMapfv},
	{"glGetPixelMapuiv", &GetPixelMapuiv},
	{"glGetPixelMapusv", &GetPixelMapusv},
	{"glGetPointerv", &GetPointerv},
	// {"glGetPointervEXT", &GetPointervEXT},
	{"glGetPolygonStipple", &GetPolygonStipple},
	// {"glGetProgramEnvParameterdvARB", &GetProgramEnvParameterdvARB},
	// {"glGetProgramEnvParameterfvARB", &GetProgramEnvParameterfvARB},
	// {"glGetProgramInfoLog", &GetProgramInfoLog},
	// {"glGetProgramiv", &GetProgramiv},
	// {"glGetProgramivARB", &GetProgramivARB},
	// {"glGetProgramivNV", &GetProgramivNV},
	// {"glGetProgramLocalParameterdvARB", &GetProgramLocalParameterdvARB},
	// {"glGetProgramLocalParameterfvARB", &GetProgramLocalParameterfvARB},
	// {"glGetProgramNamedParameterdvNV", &GetProgramNamedParameterdvNV},
	// {"glGetProgramNamedParameterfvNV", &GetProgramNamedParameterfvNV},
	// {"glGetProgramParameterdvNV", &GetProgramParameterdvNV},
	// {"glGetProgramParameterfvNV", &GetProgramParameterfvNV},
	// {"glGetProgramStringARB", &GetProgramStringARB},
	// {"glGetProgramStringNV", &GetProgramStringNV},
	// {"glGetQueryiv", &GetQueryiv},
	// {"glGetQueryivARB", &GetQueryivARB},
	// {"glGetQueryObjectiv", &GetQueryObjectiv},
	// {"glGetQueryObjectivARB", &GetQueryObjectivARB},
	// {"glGetQueryObjectuiv", &GetQueryObjectuiv},
	// {"glGetQueryObjectuivARB", &GetQueryObjectuivARB},
	// {"glGetRenderbufferParameteriv", &GetRenderbufferParameteriv},
	// {"glGetRenderbufferParameterivEXT", &GetRenderbufferParameterivEXT},
	// {"glGetSamplerParameterfv", &GetSamplerParameterfv},
	// {"glGetSamplerParameterIiv", &GetSamplerParameterIiv},
	// {"glGetSamplerParameterIuiv", &GetSamplerParameterIuiv},
	// {"glGetSamplerParameteriv", &GetSamplerParameteriv},
	// {"glGetSeparableFilter", &GetSeparableFilter},
	// {"glGetShaderInfoLog", &GetShaderInfoLog},
	// {"glGetShaderiv", &GetShaderiv},
	// {"glGetShaderPrecisionFormat", &GetShaderPrecisionFormat},
	// {"glGetShaderSource", &GetShaderSource},
	// {"glGetShaderSourceARB", &GetShaderSourceARB},
	{"glGetString", &GetString},
	// {"glGetStringi", &GetStringi},
	// {"glGetSynciv", &GetSynciv},
	// {"glGetTexBumpParameterfvATI", &GetTexBumpParameterfvATI},
	// {"glGetTexBumpParameterivATI", &GetTexBumpParameterivATI},
	{"glGetTexEnvfv", &GetTexEnvfv},
	{"glGetTexEnviv", &GetTexEnviv},
	{"glGetTexGendv", &GetTexGendv},
	{"glGetTexGenfv", &GetTexGenfv},
	{"glGetTexGeniv", &GetTexGeniv},
	{"glGetTexImage", &GetTexImage},
	{"glGetTexLevelParameterfv", &GetTexLevelParameterfv},
	{"glGetTexLevelParameteriv", &GetTexLevelParameteriv},
	{"glGetTexParameterfv", &GetTexParameterfv},
	// {"glGetTexParameterIiv", &GetTexParameterIiv},
	// {"glGetTexParameterIivEXT", &GetTexParameterIivEXT},
	// {"glGetTexParameterIuiv", &GetTexParameterIuiv},
	// {"glGetTexParameterIuivEXT", &GetTexParameterIuivEXT},
	{"glGetTexParameteriv", &GetTexParameteriv},
	// {"glGetTrackMatrixivNV", &GetTrackMatrixivNV},
	// {"glGetTransformFeedbackVarying", &GetTransformFeedbackVarying},
	// {"glGetTransformFeedbackVaryingEXT", &GetTransformFeedbackVaryingEXT},
	// {"glGetUniformfv", &GetUniformfv},
	// {"glGetUniformfvARB", &GetUniformfvARB},
	// {"glGetUniformiv", &GetUniformiv},
	// {"glGetUniformivARB", &GetUniformivARB},
	// {"glGetUniformLocation", &GetUniformLocation},
	// {"glGetUniformLocationARB", &GetUniformLocationARB},
	// {"glGetUniformuiv", &GetUniformuiv},
	// {"glGetUniformuivEXT", &GetUniformuivEXT},
	// {"glGetVertexAttribdv", &GetVertexAttribdv},
	// {"glGetVertexAttribdvARB", &GetVertexAttribdvARB},
	// {"glGetVertexAttribdvNV", &GetVertexAttribdvNV},
	// {"glGetVertexAttribfv", &GetVertexAttribfv},
	// {"glGetVertexAttribfvARB", &GetVertexAttribfvARB},
	// {"glGetVertexAttribfvNV", &GetVertexAttribfvNV},
	// {"glGetVertexAttribIiv", &GetVertexAttribIiv},
	// {"glGetVertexAttribIivEXT", &GetVertexAttribIivEXT},
	// {"glGetVertexAttribIuiv", &GetVertexAttribIuiv},
	// {"glGetVertexAttribIuivEXT", &GetVertexAttribIuivEXT},
	// {"glGetVertexAttribiv", &GetVertexAttribiv},
	// {"glGetVertexAttribivARB", &GetVertexAttribivARB},
	// {"glGetVertexAttribivNV", &GetVertexAttribivNV},
	// {"glGetVertexAttribPointerv", &GetVertexAttribPointerv},
	// {"glGetVertexAttribPointervARB", &GetVertexAttribPointervARB},
	// {"glGetVertexAttribPointervNV", &GetVertexAttribPointervNV},
	{"glHint", &Hint},
	// {"glHistogram", &Histogram},
	{"glIndexd", &Indexd},
	{"glIndexdv", &Indexdv},
	{"glIndexf", &Indexf},
	{"glIndexfv", &Indexfv},
	{"glIndexi", &Indexi},
	{"glIndexiv", &Indexiv},
	{"glIndexMask", &IndexMask},
	{"glIndexPointer", &IndexPointer},
	// {"glIndexPointerEXT", &IndexPointerEXT},
	{"glIndexs", &Indexs},
	{"glIndexsv", &Indexsv},
	{"glIndexub", &Indexub},
	{"glIndexubv", &Indexubv},
	{"glInitNames", &InitNames},
	{"glInterleavedArrays", &InterleavedArrays},
	// {"glIsBuffer", &IsBuffer},
	// {"glIsBufferARB", &IsBufferARB},
	{"glIsEnabled", &IsEnabled},
	// {"glIsEnabledi", &IsEnabledi},
	// {"glIsEnabledIndexedEXT", &IsEnabledIndexedEXT},
	// {"glIsFramebuffer", &IsFramebuffer},
	// {"glIsFramebufferEXT", &IsFramebufferEXT},
	{"glIsList", &IsList},
	// {"glIsProgram", &IsProgram},
	// {"glIsProgramARB", &IsProgramARB},
	// {"glIsProgramNV", &IsProgramNV},
	// {"glIsQuery", &IsQuery},
	// {"glIsQueryARB", &IsQueryARB},
	// {"glIsRenderbuffer", &IsRenderbuffer},
	// {"glIsRenderbufferEXT", &IsRenderbufferEXT},
	// {"glIsSampler", &IsSampler},
	// {"glIsShader", &IsShader},
	// {"glIsSync", &IsSync},
	{"glIsTexture", &IsTexture},
	// {"glIsTextureEXT", &IsTextureEXT},
	// {"glIsTransformFeedback", &IsTransformFeedback},
	// {"glIsVertexArray", &IsVertexArray},
	{"glLightf", &Lightf},
	{"glLightfv", &Lightfv},
	{"glLighti", &Lighti},
	{"glLightiv", &Lightiv},
	{"glLightModelf", &LightModelf},
	{"glLightModelfv", &LightModelfv},
	{"glLightModeli", &LightModeli},
	{"glLightModeliv", &LightModeliv},
	{"glLineStipple", &LineStipple},
	{"glLineWidth", &LineWidth},
	// {"glLinkProgram", &LinkProgram},
	// {"glLinkProgramARB", &LinkProgramARB},
	{"glListBase", &ListBase},
	{"glLoadIdentity", &LoadIdentity},
	{"glLoadMatrixd", &LoadMatrixd},
	{"glLoadMatrixf", &LoadMatrixf},
	{"glLoadName", &LoadName},
	// {"glLoadProgramNV", &LoadProgramNV},
	// {"glLoadTransposeMatrixd", &LoadTransposeMatrixd},
	// {"glLoadTransposeMatrixdARB", &LoadTransposeMatrixdARB},
	// {"glLoadTransposeMatrixf", &LoadTransposeMatrixf},
	// {"glLoadTransposeMatrixfARB", &LoadTransposeMatrixfARB},
	// {"glLockArraysEXT", &LockArraysEXT},
	{"glLogicOp", &LogicOp},
	{"glMap1d", &Map1d},
	{"glMap1f", &Map1f},
	{"glMap2d", &Map2d},
	{"glMap2f", &Map2f},
	// {"glMapBuffer", &MapBuffer},
	// {"glMapBufferARB", &MapBufferARB},
	// {"glMapBufferRange", &MapBufferRange},
	{"glMapGrid1d", &MapGrid1d},
	{"glMapGrid1f", &MapGrid1f},
	{"glMapGrid2d", &MapGrid2d},
	{"glMapGrid2f", &MapGrid2f},
	{"glMaterialf", &Materialf},
	{"glMaterialfv", &Materialfv},
	{"glMateriali", &Materiali},
	{"glMaterialiv", &Materialiv},
	{"glMatrixMode", &MatrixMode},
	// {"glMinmax", &Minmax},
	// {"glMultiDrawArrays", &MultiDrawArrays},
	// {"glMultiDrawArraysEXT", &MultiDrawArraysEXT},
	// {"glMultiDrawElements", &MultiDrawElements},
	// {"glMultiDrawElementsBaseVertex", &MultiDrawElementsBaseVertex},
	// {"glMultiDrawElementsEXT", &MultiDrawElementsEXT},
	// {"glMultiTexCoord1d", &MultiTexCoord1d},
	// {"glMultiTexCoord1dARB", &MultiTexCoord1dARB},
	// {"glMultiTexCoord1dv", &MultiTexCoord1dv},
	// {"glMultiTexCoord1dvARB", &MultiTexCoord1dvARB},
	// {"glMultiTexCoord1f", &MultiTexCoord1f},
	// {"glMultiTexCoord1fARB", &MultiTexCoord1fARB},
	// {"glMultiTexCoord1fv", &MultiTexCoord1fv},
	// {"glMultiTexCoord1fvARB", &MultiTexCoord1fvARB},
	// {"glMultiTexCoord1i", &MultiTexCoord1i},
	// {"glMultiTexCoord1iARB", &MultiTexCoord1iARB},
	// {"glMultiTexCoord1iv", &MultiTexCoord1iv},
	// {"glMultiTexCoord1ivARB", &MultiTexCoord1ivARB},
	// {"glMultiTexCoord1s", &MultiTexCoord1s},
	// {"glMultiTexCoord1sARB", &MultiTexCoord1sARB},
	// {"glMultiTexCoord1sv", &MultiTexCoord1sv},
	// {"glMultiTexCoord1svARB", &MultiTexCoord1svARB},
	// {"glMultiTexCoord2d", &MultiTexCoord2d},
	// {"glMultiTexCoord2dARB", &MultiTexCoord2dARB},
	// {"glMultiTexCoord2dv", &MultiTexCoord2dv},
	// {"glMultiTexCoord2dvARB", &MultiTexCoord2dvARB},
	// {"glMultiTexCoord2f", &MultiTexCoord2f},
	// {"glMultiTexCoord2fARB", &MultiTexCoord2fARB},
	// {"glMultiTexCoord2fv", &MultiTexCoord2fv},
	// {"glMultiTexCoord2fvARB", &MultiTexCoord2fvARB},
	// {"glMultiTexCoord2i", &MultiTexCoord2i},
	// {"glMultiTexCoord2iARB", &MultiTexCoord2iARB},
	// {"glMultiTexCoord2iv", &MultiTexCoord2iv},
	// {"glMultiTexCoord2ivARB", &MultiTexCoord2ivARB},
	// {"glMultiTexCoord2s", &MultiTexCoord2s},
	// {"glMultiTexCoord2sARB", &MultiTexCoord2sARB},
	// {"glMultiTexCoord2sv", &MultiTexCoord2sv},
	// {"glMultiTexCoord2svARB", &MultiTexCoord2svARB},
	// {"glMultiTexCoord3d", &MultiTexCoord3d},
	// {"glMultiTexCoord3dARB", &MultiTexCoord3dARB},
	// {"glMultiTexCoord3dv", &MultiTexCoord3dv},
	// {"glMultiTexCoord3dvARB", &MultiTexCoord3dvARB},
	// {"glMultiTexCoord3f", &MultiTexCoord3f},
	// {"glMultiTexCoord3fARB", &MultiTexCoord3fARB},
	// {"glMultiTexCoord3fv", &MultiTexCoord3fv},
	// {"glMultiTexCoord3fvARB", &MultiTexCoord3fvARB},
	// {"glMultiTexCoord3i", &MultiTexCoord3i},
	// {"glMultiTexCoord3iARB", &MultiTexCoord3iARB},
	// {"glMultiTexCoord3iv", &MultiTexCoord3iv},
	// {"glMultiTexCoord3ivARB", &MultiTexCoord3ivARB},
	// {"glMultiTexCoord3s", &MultiTexCoord3s},
	// {"glMultiTexCoord3sARB", &MultiTexCoord3sARB},
	// {"glMultiTexCoord3sv", &MultiTexCoord3sv},
	// {"glMultiTexCoord3svARB", &MultiTexCoord3svARB},
	// {"glMultiTexCoord4d", &MultiTexCoord4d},
	// {"glMultiTexCoord4dARB", &MultiTexCoord4dARB},
	// {"glMultiTexCoord4dv", &MultiTexCoord4dv},
	// {"glMultiTexCoord4dvARB", &MultiTexCoord4dvARB},
	// {"glMultiTexCoord4f", &MultiTexCoord4f},
	// {"glMultiTexCoord4fARB", &MultiTexCoord4fARB},
	// {"glMultiTexCoord4fv", &MultiTexCoord4fv},
	// {"glMultiTexCoord4fvARB", &MultiTexCoord4fvARB},
	// {"glMultiTexCoord4i", &MultiTexCoord4i},
	// {"glMultiTexCoord4iARB", &MultiTexCoord4iARB},
	// {"glMultiTexCoord4iv", &MultiTexCoord4iv},
	// {"glMultiTexCoord4ivARB", &MultiTexCoord4ivARB},
	// {"glMultiTexCoord4s", &MultiTexCoord4s},
	// {"glMultiTexCoord4sARB", &MultiTexCoord4sARB},
	// {"glMultiTexCoord4sv", &MultiTexCoord4sv},
	// {"glMultiTexCoord4svARB", &MultiTexCoord4svARB},
	// {"glMultiTexCoordP1ui", &MultiTexCoordP1ui},
	// {"glMultiTexCoordP1uiv", &MultiTexCoordP1uiv},
	// {"glMultiTexCoordP2ui", &MultiTexCoordP2ui},
	// {"glMultiTexCoordP2uiv", &MultiTexCoordP2uiv},
	// {"glMultiTexCoordP3ui", &MultiTexCoordP3ui},
	// {"glMultiTexCoordP3uiv", &MultiTexCoordP3uiv},
	// {"glMultiTexCoordP4ui", &MultiTexCoordP4ui},
	// {"glMultiTexCoordP4uiv", &MultiTexCoordP4uiv},
	{"glMultMatrixd", &MultMatrixd},
	{"glMultMatrixf", &MultMatrixf},
	// {"glMultTransposeMatrixd", &MultTransposeMatrixd},
	// {"glMultTransposeMatrixdARB", &MultTransposeMatrixdARB},
	// {"glMultTransposeMatrixf", &MultTransposeMatrixf},
	// {"glMultTransposeMatrixfARB", &MultTransposeMatrixfARB},
	{"glNewList", &NewList},
	{"glNormal3b", &Normal3b},
	{"glNormal3bv", &Normal3bv},
	{"glNormal3d", &Normal3d},
	{"glNormal3dv", &Normal3dv},
	{"glNormal3f", &Normal3f},
	{"glNormal3fv", &Normal3fv},
	{"glNormal3i", &Normal3i},
	{"glNormal3iv", &Normal3iv},
	{"glNormal3s", &Normal3s},
	{"glNormal3sv", &Normal3sv},
	// {"glNormalP3ui", &NormalP3ui},
	// {"glNormalP3uiv", &NormalP3uiv},
	{"glNormalPointer", &NormalPointer},
	// {"glNormalPointerEXT", &NormalPointerEXT},
	// {"glObjectPurgeableAPPLE", &ObjectPurgeableAPPLE},
	// {"glObjectUnpurgeableAPPLE", &ObjectUnpurgeableAPPLE},
	{"glOrtho", &Ortho},
	// {"glPassTexCoordATI", &PassTexCoordATI},
	{"glPassThrough", &PassThrough},
	// {"glPauseTransformFeedback", &PauseTransformFeedback},
	{"glPixelMapfv", &PixelMapfv},
	{"glPixelMapuiv", &PixelMapuiv},
	{"glPixelMapusv", &PixelMapusv},
	{"glPixelStoref", &PixelStoref},
	{"glPixelStorei", &PixelStorei},
	{"glPixelTransferf", &PixelTransferf},
	{"glPixelTransferi", &PixelTransferi},
	{"glPixelZoom", &PixelZoom},
	// {"glPointParameterf", &PointParameterf},
	// {"glPointParameterfARB", &PointParameterfARB},
	// {"glPointParameterfEXT", &PointParameterfEXT},
	// {"glPointParameterfv", &PointParameterfv},
	// {"glPointParameterfvARB", &PointParameterfvARB},
	// {"glPointParameterfvEXT", &PointParameterfvEXT},
	// {"glPointParameteri", &PointParameteri},
	// {"glPointParameteriNV", &PointParameteriNV},
	// {"glPointParameteriv", &PointParameteriv},
	// {"glPointParameterivNV", &PointParameterivNV},
	{"glPointSize", &PointSize},
	{"glPolygonMode", &PolygonMode},
	{"glPolygonOffset", &PolygonOffset},
	// {"glPolygonOffsetEXT", &PolygonOffsetEXT},
	{"glPolygonStipple", &PolygonStipple},
	{"glPopAttrib", &PopAttrib},
	{"glPopClientAttrib", &PopClientAttrib},
	{"glPopMatrix", &PopMatrix},
	{"glPopName", &PopName},
	// {"glPrimitiveRestartIndex", &PrimitiveRestartIndex},
	// {"glPrimitiveRestartIndexNV", &PrimitiveRestartIndexNV},
	// {"glPrimitiveRestartNV", &PrimitiveRestartNV},
	{"glPrioritizeTextures", &PrioritizeTextures},
	// {"glPrioritizeTexturesEXT", &PrioritizeTexturesEXT},
	// {"glProgramEnvParameter4dARB", &ProgramEnvParameter4dARB},
	// {"glProgramEnvParameter4dvARB", &ProgramEnvParameter4dvARB},
	// {"glProgramEnvParameter4fARB", &ProgramEnvParameter4fARB},
	// {"glProgramEnvParameter4fvARB", &ProgramEnvParameter4fvARB},
	// {"glProgramLocalParameter4dARB", &ProgramLocalParameter4dARB},
	// {"glProgramLocalParameter4dvARB", &ProgramLocalParameter4dvARB},
	// {"glProgramLocalParameter4fARB", &ProgramLocalParameter4fARB},
	// {"glProgramLocalParameter4fvARB", &ProgramLocalParameter4fvARB},
	// {"glProgramNamedParameter4dNV", &ProgramNamedParameter4dNV},
	// {"glProgramNamedParameter4dvNV", &ProgramNamedParameter4dvNV},
	// {"glProgramNamedParameter4fNV", &ProgramNamedParameter4fNV},
	// {"glProgramNamedParameter4fvNV", &ProgramNamedParameter4fvNV},
	// {"glProgramParameter4dNV", &ProgramParameter4dNV},
	// {"glProgramParameter4dvNV", &ProgramParameter4dvNV},
	// {"glProgramParameter4fNV", &ProgramParameter4fNV},
	// {"glProgramParameter4fvNV", &ProgramParameter4fvNV},
	// {"glProgramParameteriARB", &ProgramParameteriARB},
	// {"glProgramParameters4dvNV", &ProgramParameters4dvNV},
	// {"glProgramParameters4fvNV", &ProgramParameters4fvNV},
	// {"glProgramStringARB", &ProgramStringARB},
	// {"glProvokingVertex", &ProvokingVertex},
	// {"glProvokingVertexEXT", &ProvokingVertexEXT},
	{"glPushAttrib", &PushAttrib},
	{"glPushClientAttrib", &PushClientAttrib},
	{"glPushMatrix", &PushMatrix},
	{"glPushName", &PushName},
	{"glRasterPos2d", &RasterPos2d},
	{"glRasterPos2dv", &RasterPos2dv},
	{"glRasterPos2f", &RasterPos2f},
	{"glRasterPos2fv", &RasterPos2fv},
	{"glRasterPos2i", &RasterPos2i},
	{"glRasterPos2iv", &RasterPos2iv},
	{"glRasterPos2s", &RasterPos2s},
	{"glRasterPos2sv", &RasterPos2sv},
	{"glRasterPos3d", &RasterPos3d},
	{"glRasterPos3dv", &RasterPos3dv},
	{"glRasterPos3f", &RasterPos3f},
	{"glRasterPos3fv", &RasterPos3fv},
	{"glRasterPos3i", &RasterPos3i},
	{"glRasterPos3iv", &RasterPos3iv},
	{"glRasterPos3s", &RasterPos3s},
	{"glRasterPos3sv", &RasterPos3sv},
	{"glRasterPos4d", &RasterPos4d},
	{"glRasterPos4dv", &RasterPos4dv},
	{"glRasterPos4f", &RasterPos4f},
	{"glRasterPos4fv", &RasterPos4fv},
	{"glRasterPos4i", &RasterPos4i},
	{"glRasterPos4iv", &RasterPos4iv},
	{"glRasterPos4s", &RasterPos4s},
	{"glRasterPos4sv", &RasterPos4sv},
	{"glReadBuffer", &ReadBuffer},
	// {"glReadnPixelsARB", &ReadnPixelsARB},
	{"glReadPixels", &ReadPixels},
	{"glRectd", &Rectd},
	{"glRectdv", &Rectdv},
	{"glRectf", &Rectf},
	{"glRectfv", &Rectfv},
	{"glRecti", &Recti},
	{"glRectiv", &Rectiv},
	{"glRects", &Rects},
	{"glRectsv", &Rectsv},
	// {"glReleaseShaderCompiler", &ReleaseShaderCompiler},
	// {"glRenderbufferStorage", &RenderbufferStorage},
	// {"glRenderbufferStorageEXT", &RenderbufferStorageEXT},
	// {"glRenderbufferStorageMultisample", &RenderbufferStorageMultisample},
	// {"glRenderbufferStorageMultisampleEXT", &RenderbufferStorageMultisampleEXT},
	{"glRenderMode", &RenderMode},
	// {"glRequestResidentProgramsNV", &RequestResidentProgramsNV},
	// {"glResetHistogram", &ResetHistogram},
	// {"glResetMinmax", &ResetMinmax},
	// {"glResizeBuffersMESA", &ResizeBuffersMESA},
	// {"glResumeTransformFeedback", &ResumeTransformFeedback},
	{"glRotated", &Rotated},
	{"glRotatef", &Rotatef},
	// {"glSampleCoverage", &SampleCoverage},
	// {"glSampleCoverageARB", &SampleCoverageARB},
	// {"glSampleMapATI", &SampleMapATI},
	// {"glSamplerParameterf", &SamplerParameterf},
	// {"glSamplerParameterfv", &SamplerParameterfv},
	// {"glSamplerParameteri", &SamplerParameteri},
	// {"glSamplerParameterIiv", &SamplerParameterIiv},
	// {"glSamplerParameterIuiv", &SamplerParameterIuiv},
	// {"glSamplerParameteriv", &SamplerParameteriv},
	{"glScaled", &Scaled},
	{"glScalef", &Scalef},
	{"glScissor", &Scissor},
	// {"glSecondaryColor3b", &SecondaryColor3b},
	// {"glSecondaryColor3bEXT", &SecondaryColor3bEXT},
	// {"glSecondaryColor3bv", &SecondaryColor3bv},
	// {"glSecondaryColor3bvEXT", &SecondaryColor3bvEXT},
	// {"glSecondaryColor3d", &SecondaryColor3d},
	// {"glSecondaryColor3dEXT", &SecondaryColor3dEXT},
	// {"glSecondaryColor3dv", &SecondaryColor3dv},
	// {"glSecondaryColor3dvEXT", &SecondaryColor3dvEXT},
	// {"glSecondaryColor3f", &SecondaryColor3f},
	// {"glSecondaryColor3fEXT", &SecondaryColor3fEXT},
	// {"glSecondaryColor3fv", &SecondaryColor3fv},
	// {"glSecondaryColor3fvEXT", &SecondaryColor3fvEXT},
	// {"glSecondaryColor3i", &SecondaryColor3i},
	// {"glSecondaryColor3iEXT", &SecondaryColor3iEXT},
	// {"glSecondaryColor3iv", &SecondaryColor3iv},
	// {"glSecondaryColor3ivEXT", &SecondaryColor3ivEXT},
	// {"glSecondaryColor3s", &SecondaryColor3s},
	// {"glSecondaryColor3sEXT", &SecondaryColor3sEXT},
	// {"glSecondaryColor3sv", &SecondaryColor3sv},
	// {"glSecondaryColor3svEXT", &SecondaryColor3svEXT},
	// {"glSecondaryColor3ub", &SecondaryColor3ub},
	// {"glSecondaryColor3ubEXT", &SecondaryColor3ubEXT},
	// {"glSecondaryColor3ubv", &SecondaryColor3ubv},
	// {"glSecondaryColor3ubvEXT", &SecondaryColor3ubvEXT},
	// {"glSecondaryColor3ui", &SecondaryColor3ui},
	// {"glSecondaryColor3uiEXT", &SecondaryColor3uiEXT},
	// {"glSecondaryColor3uiv", &SecondaryColor3uiv},
	// {"glSecondaryColor3uivEXT", &SecondaryColor3uivEXT},
	// {"glSecondaryColor3us", &SecondaryColor3us},
	// {"glSecondaryColor3usEXT", &SecondaryColor3usEXT},
	// {"glSecondaryColor3usv", &SecondaryColor3usv},
	// {"glSecondaryColor3usvEXT", &SecondaryColor3usvEXT},
	// {"glSecondaryColorP3ui", &SecondaryColorP3ui},
	// {"glSecondaryColorP3uiv", &SecondaryColorP3uiv},
	// {"glSecondaryColorPointer", &SecondaryColorPointer},
	// {"glSecondaryColorPointerEXT", &SecondaryColorPointerEXT},
	{"glSelectBuffer", &SelectBuffer},
	// {"glSeparableFilter2D", &SeparableFilter2D},
	// {"glSetFragmentShaderConstantATI", &SetFragmentShaderConstantATI},
	{"glShadeModel", &ShadeModel},
	// {"glShaderBinary", &ShaderBinary},
	// {"glShaderSource", &ShaderSource},
	// {"glShaderSourceARB", &ShaderSourceARB},
	{"glStencilFunc", &StencilFunc},
	// {"glStencilFuncSeparate", &StencilFuncSeparate},
	{"glStencilMask", &StencilMask},
	// {"glStencilMaskSeparate", &StencilMaskSeparate},
	{"glStencilOp", &StencilOp},
	// {"glStencilOpSeparate", &StencilOpSeparate},
	// {"glTexBuffer", &TexBuffer},
	// {"glTexBufferARB", &TexBufferARB},
	// {"glTexBumpParameterfvATI", &TexBumpParameterfvATI},
	// {"glTexBumpParameterivATI", &TexBumpParameterivATI},
	{"glTexCoord1d", &TexCoord1d},
	{"glTexCoord1dv", &TexCoord1dv},
	{"glTexCoord1f", &TexCoord1f},
	{"glTexCoord1fv", &TexCoord1fv},
	{"glTexCoord1i", &TexCoord1i},
	{"glTexCoord1iv", &TexCoord1iv},
	{"glTexCoord1s", &TexCoord1s},
	{"glTexCoord1sv", &TexCoord1sv},
	{"glTexCoord2d", &TexCoord2d},
	{"glTexCoord2dv", &TexCoord2dv},
	{"glTexCoord2f", &TexCoord2f},
	{"glTexCoord2fv", &TexCoord2fv},
	{"glTexCoord2i", &TexCoord2i},
	{"glTexCoord2iv", &TexCoord2iv},
	{"glTexCoord2s", &TexCoord2s},
	{"glTexCoord2sv", &TexCoord2sv},
	{"glTexCoord3d", &TexCoord3d},
	{"glTexCoord3dv", &TexCoord3dv},
	{"glTexCoord3f", &TexCoord3f},
	{"glTexCoord3fv", &TexCoord3fv},
	{"glTexCoord3i", &TexCoord3i},
	{"glTexCoord3iv", &TexCoord3iv},
	{"glTexCoord3s", &TexCoord3s},
	{"glTexCoord3sv", &TexCoord3sv},
	{"glTexCoord4d", &TexCoord4d},
	{"glTexCoord4dv", &TexCoord4dv},
	{"glTexCoord4f", &TexCoord4f},
	{"glTexCoord4fv", &TexCoord4fv},
	{"glTexCoord4i", &TexCoord4i},
	{"glTexCoord4iv", &TexCoord4iv},
	{"glTexCoord4s", &TexCoord4s},
	{"glTexCoord4sv", &TexCoord4sv},
	// {"glTexCoordP1ui", &TexCoordP1ui},
	// {"glTexCoordP1uiv", &TexCoordP1uiv},
	// {"glTexCoordP2ui", &TexCoordP2ui},
	// {"glTexCoordP2uiv", &TexCoordP2uiv},
	// {"glTexCoordP3ui", &TexCoordP3ui},
	// {"glTexCoordP3uiv", &TexCoordP3uiv},
	// {"glTexCoordP4ui", &TexCoordP4ui},
	// {"glTexCoordP4uiv", &TexCoordP4uiv},
	{"glTexCoordPointer", &TexCoordPointer},
	// {"glTexCoordPointerEXT", &TexCoordPointerEXT},
	{"glTexEnvf", &TexEnvf},
	{"glTexEnvfv", &TexEnvfv},
	{"glTexEnvi", &TexEnvi},
	{"glTexEnviv", &TexEnviv},
	{"glTexGend", &TexGend},
	{"glTexGendv", &TexGendv},
	{"glTexGenf", &TexGenf},
	{"glTexGenfv", &TexGenfv},
	{"glTexGeni", &TexGeni},
	{"glTexGeniv", &TexGeniv},
	{"glTexImage1D", &TexImage1D},
	{"glTexImage2D", &TexImage2D},
	// {"glTexImage3D", &TexImage3D},
	// {"glTexImage3DEXT", &TexImage3DEXT},
	{"glTexParameterf", &TexParameterf},
	{"glTexParameterfv", &TexParameterfv},
	{"glTexParameteri", &TexParameteri},
	// {"glTexParameterIiv", &TexParameterIiv},
	// {"glTexParameterIivEXT", &TexParameterIivEXT},
	// {"glTexParameterIuiv", &TexParameterIuiv},
	// {"glTexParameterIuivEXT", &TexParameterIuivEXT},
	{"glTexParameteriv", &TexParameteriv},
	// {"glTexStorage1D", &TexStorage1D},
	// {"glTexStorage2D", &TexStorage2D},
	// {"glTexStorage3D", &TexStorage3D},
	{"glTexSubImage1D", &TexSubImage1D},
	// {"glTexSubImage1DEXT", &TexSubImage1DEXT},
	{"glTexSubImage2D", &TexSubImage2D},
	// {"glTexSubImage2DEXT", &TexSubImage2DEXT},
	// {"glTexSubImage3D", &TexSubImage3D},
	// {"glTexSubImage3DEXT", &TexSubImage3DEXT},
	// {"glTextureBarrierNV", &TextureBarrierNV},
	// {"glTextureStorage1DEXT", &TextureStorage1DEXT},
	// {"glTextureStorage2DEXT", &TextureStorage2DEXT},
	// {"glTextureStorage3DEXT", &TextureStorage3DEXT},
	// {"glTrackMatrixNV", &TrackMatrixNV},
	// {"glTransformFeedbackVaryings", &TransformFeedbackVaryings},
	// {"glTransformFeedbackVaryingsEXT", &TransformFeedbackVaryingsEXT},
	{"glTranslated", &Translated},
	{"glTranslatef", &Translatef},
	// {"glUniform1f", &Uniform1f},
	// {"glUniform1fARB", &Uniform1fARB},
	// {"glUniform1fv", &Uniform1fv},
	// {"glUniform1fvARB", &Uniform1fvARB},
	// {"glUniform1i", &Uniform1i},
	// {"glUniform1iARB", &Uniform1iARB},
	// {"glUniform1iv", &Uniform1iv},
	// {"glUniform1ivARB", &Uniform1ivARB},
	// {"glUniform1ui", &Uniform1ui},
	// {"glUniform1uiEXT", &Uniform1uiEXT},
	// {"glUniform1uiv", &Uniform1uiv},
	// {"glUniform1uivEXT", &Uniform1uivEXT},
	// {"glUniform2f", &Uniform2f},
	// {"glUniform2fARB", &Uniform2fARB},
	// {"glUniform2fv", &Uniform2fv},
	// {"glUniform2fvARB", &Uniform2fvARB},
	// {"glUniform2i", &Uniform2i},
	// {"glUniform2iARB", &Uniform2iARB},
	// {"glUniform2iv", &Uniform2iv},
	// {"glUniform2ivARB", &Uniform2ivARB},
	// {"glUniform2ui", &Uniform2ui},
	// {"glUniform2uiEXT", &Uniform2uiEXT},
	// {"glUniform2uiv", &Uniform2uiv},
	// {"glUniform2uivEXT", &Uniform2uivEXT},
	// {"glUniform3f", &Uniform3f},
	// {"glUniform3fARB", &Uniform3fARB},
	// {"glUniform3fv", &Uniform3fv},
	// {"glUniform3fvARB", &Uniform3fvARB},
	// {"glUniform3i", &Uniform3i},
	// {"glUniform3iARB", &Uniform3iARB},
	// {"glUniform3iv", &Uniform3iv},
	// {"glUniform3ivARB", &Uniform3ivARB},
	// {"glUniform3ui", &Uniform3ui},
	// {"glUniform3uiEXT", &Uniform3uiEXT},
	// {"glUniform3uiv", &Uniform3uiv},
	// {"glUniform3uivEXT", &Uniform3uivEXT},
	// {"glUniform4f", &Uniform4f},
	// {"glUniform4fARB", &Uniform4fARB},
	// {"glUniform4fv", &Uniform4fv},
	// {"glUniform4fvARB", &Uniform4fvARB},
	// {"glUniform4i", &Uniform4i},
	// {"glUniform4iARB", &Uniform4iARB},
	// {"glUniform4iv", &Uniform4iv},
	// {"glUniform4ivARB", &Uniform4ivARB},
	// {"glUniform4ui", &Uniform4ui},
	// {"glUniform4uiEXT", &Uniform4uiEXT},
	// {"glUniform4uiv", &Uniform4uiv},
	// {"glUniform4uivEXT", &Uniform4uivEXT},
	// {"glUniformMatrix2fv", &UniformMatrix2fv},
	// {"glUniformMatrix2fvARB", &UniformMatrix2fvARB},
	// {"glUniformMatrix2x3fv", &UniformMatrix2x3fv},
	// {"glUniformMatrix2x4fv", &UniformMatrix2x4fv},
	// {"glUniformMatrix3fv", &UniformMatrix3fv},
	// {"glUniformMatrix3fvARB", &UniformMatrix3fvARB},
	// {"glUniformMatrix3x2fv", &UniformMatrix3x2fv},
	// {"glUniformMatrix3x4fv", &UniformMatrix3x4fv},
	// {"glUniformMatrix4fv", &UniformMatrix4fv},
	// {"glUniformMatrix4fvARB", &UniformMatrix4fvARB},
	// {"glUniformMatrix4x2fv", &UniformMatrix4x2fv},
	// {"glUniformMatrix4x3fv", &UniformMatrix4x3fv},
	// {"glUnlockArraysEXT", &UnlockArraysEXT},
	// {"glUnmapBuffer", &UnmapBuffer},
	// {"glUnmapBufferARB", &UnmapBufferARB},
	// {"glUseProgram", &UseProgram},
	// {"glUseProgramObjectARB", &UseProgramObjectARB},
	// {"glUseShaderProgramEXT", &UseShaderProgramEXT},
	// {"glValidateProgram", &ValidateProgram},
	// {"glValidateProgramARB", &ValidateProgramARB},
	{"glVertex2d", &Vertex2d},
	{"glVertex2dv", &Vertex2dv},
	{"glVertex2f", &Vertex2f},
	{"glVertex2fv", &Vertex2fv},
	{"glVertex2i", &Vertex2i},
	{"glVertex2iv", &Vertex2iv},
	{"glVertex2s", &Vertex2s},
	{"glVertex2sv", &Vertex2sv},
	{"glVertex3d", &Vertex3d},
	{"glVertex3dv", &Vertex3dv},
	{"glVertex3f", &Vertex3f},
	{"glVertex3fv", &Vertex3fv},
	{"glVertex3i", &Vertex3i},
	{"glVertex3iv", &Vertex3iv},
	{"glVertex3s", &Vertex3s},
	{"glVertex3sv", &Vertex3sv},
	{"glVertex4d", &Vertex4d},
	{"glVertex4dv", &Vertex4dv},
	{"glVertex4f", &Vertex4f},
	{"glVertex4fv", &Vertex4fv},
	{"glVertex4i", &Vertex4i},
	{"glVertex4iv", &Vertex4iv},
	{"glVertex4s", &Vertex4s},
	{"glVertex4sv", &Vertex4sv},
	// {"glVertexArrayRangeNV", &VertexArrayRangeNV},
	// {"glVertexAttrib1d", &VertexAttrib1d},
	// {"glVertexAttrib1dARB", &VertexAttrib1dARB},
	// {"glVertexAttrib1dNV", &VertexAttrib1dNV},
	// {"glVertexAttrib1dv", &VertexAttrib1dv},
	// {"glVertexAttrib1dvARB", &VertexAttrib1dvARB},
	// {"glVertexAttrib1dvNV", &VertexAttrib1dvNV},
	// {"glVertexAttrib1f", &VertexAttrib1f},
	// {"glVertexAttrib1fARB", &VertexAttrib1fARB},
	// {"glVertexAttrib1fNV", &VertexAttrib1fNV},
	// {"glVertexAttrib1fv", &VertexAttrib1fv},
	// {"glVertexAttrib1fvARB", &VertexAttrib1fvARB},
	// {"glVertexAttrib1fvNV", &VertexAttrib1fvNV},
	// {"glVertexAttrib1s", &VertexAttrib1s},
	// {"glVertexAttrib1sARB", &VertexAttrib1sARB},
	// {"glVertexAttrib1sNV", &VertexAttrib1sNV},
	// {"glVertexAttrib1sv", &VertexAttrib1sv},
	// {"glVertexAttrib1svARB", &VertexAttrib1svARB},
	// {"glVertexAttrib1svNV", &VertexAttrib1svNV},
	// {"glVertexAttrib2d", &VertexAttrib2d},
	// {"glVertexAttrib2dARB", &VertexAttrib2dARB},
	// {"glVertexAttrib2dNV", &VertexAttrib2dNV},
	// {"glVertexAttrib2dv", &VertexAttrib2dv},
	// {"glVertexAttrib2dvARB", &VertexAttrib2dvARB},
	// {"glVertexAttrib2dvNV", &VertexAttrib2dvNV},
	// {"glVertexAttrib2f", &VertexAttrib2f},
	// {"glVertexAttrib2fARB", &VertexAttrib2fARB},
	// {"glVertexAttrib2fNV", &VertexAttrib2fNV},
	// {"glVertexAttrib2fv", &VertexAttrib2fv},
	// {"glVertexAttrib2fvARB", &VertexAttrib2fvARB},
	// {"glVertexAttrib2fvNV", &VertexAttrib2fvNV},
	// {"glVertexAttrib2s", &VertexAttrib2s},
	// {"glVertexAttrib2sARB", &VertexAttrib2sARB},
	// {"glVertexAttrib2sNV", &VertexAttrib2sNV},
	// {"glVertexAttrib2sv", &VertexAttrib2sv},
	// {"glVertexAttrib2svARB", &VertexAttrib2svARB},
	// {"glVertexAttrib2svNV", &VertexAttrib2svNV},
	// {"glVertexAttrib3d", &VertexAttrib3d},
	// {"glVertexAttrib3dARB", &VertexAttrib3dARB},
	// {"glVertexAttrib3dNV", &VertexAttrib3dNV},
	// {"glVertexAttrib3dv", &VertexAttrib3dv},
	// {"glVertexAttrib3dvARB", &VertexAttrib3dvARB},
	// {"glVertexAttrib3dvNV", &VertexAttrib3dvNV},
	// {"glVertexAttrib3f", &VertexAttrib3f},
	// {"glVertexAttrib3fARB", &VertexAttrib3fARB},
	// {"glVertexAttrib3fNV", &VertexAttrib3fNV},
	// {"glVertexAttrib3fv", &VertexAttrib3fv},
	// {"glVertexAttrib3fvARB", &VertexAttrib3fvARB},
	// {"glVertexAttrib3fvNV", &VertexAttrib3fvNV},
	// {"glVertexAttrib3s", &VertexAttrib3s},
	// {"glVertexAttrib3sARB", &VertexAttrib3sARB},
	// {"glVertexAttrib3sNV", &VertexAttrib3sNV},
	// {"glVertexAttrib3sv", &VertexAttrib3sv},
	// {"glVertexAttrib3svARB", &VertexAttrib3svARB},
	// {"glVertexAttrib3svNV", &VertexAttrib3svNV},
	// {"glVertexAttrib4bv", &VertexAttrib4bv},
	// {"glVertexAttrib4bvARB", &VertexAttrib4bvARB},
	// {"glVertexAttrib4d", &VertexAttrib4d},
	// {"glVertexAttrib4dARB", &VertexAttrib4dARB},
	// {"glVertexAttrib4dNV", &VertexAttrib4dNV},
	// {"glVertexAttrib4dv", &VertexAttrib4dv},
	// {"glVertexAttrib4dvARB", &VertexAttrib4dvARB},
	// {"glVertexAttrib4dvNV", &VertexAttrib4dvNV},
	// {"glVertexAttrib4f", &VertexAttrib4f},
	// {"glVertexAttrib4fARB", &VertexAttrib4fARB},
	// {"glVertexAttrib4fNV", &VertexAttrib4fNV},
	// {"glVertexAttrib4fv", &VertexAttrib4fv},
	// {"glVertexAttrib4fvARB", &VertexAttrib4fvARB},
	// {"glVertexAttrib4fvNV", &VertexAttrib4fvNV},
	// {"glVertexAttrib4iv", &VertexAttrib4iv},
	// {"glVertexAttrib4ivARB", &VertexAttrib4ivARB},
	// {"glVertexAttrib4Nbv", &VertexAttrib4Nbv},
	// {"glVertexAttrib4NbvARB", &VertexAttrib4NbvARB},
	// {"glVertexAttrib4Niv", &VertexAttrib4Niv},
	// {"glVertexAttrib4NivARB", &VertexAttrib4NivARB},
	// {"glVertexAttrib4Nsv", &VertexAttrib4Nsv},
	// {"glVertexAttrib4NsvARB", &VertexAttrib4NsvARB},
	// {"glVertexAttrib4Nub", &VertexAttrib4Nub},
	// {"glVertexAttrib4NubARB", &VertexAttrib4NubARB},
	// {"glVertexAttrib4Nubv", &VertexAttrib4Nubv},
	// {"glVertexAttrib4NubvARB", &VertexAttrib4NubvARB},
	// {"glVertexAttrib4Nuiv", &VertexAttrib4Nuiv},
	// {"glVertexAttrib4NuivARB", &VertexAttrib4NuivARB},
	// {"glVertexAttrib4Nusv", &VertexAttrib4Nusv},
	// {"glVertexAttrib4NusvARB", &VertexAttrib4NusvARB},
	// {"glVertexAttrib4s", &VertexAttrib4s},
	// {"glVertexAttrib4sARB", &VertexAttrib4sARB},
	// {"glVertexAttrib4sNV", &VertexAttrib4sNV},
	// {"glVertexAttrib4sv", &VertexAttrib4sv},
	// {"glVertexAttrib4svARB", &VertexAttrib4svARB},
	// {"glVertexAttrib4svNV", &VertexAttrib4svNV},
	// {"glVertexAttrib4ubNV", &VertexAttrib4ubNV},
	// {"glVertexAttrib4ubv", &VertexAttrib4ubv},
	// {"glVertexAttrib4ubvARB", &VertexAttrib4ubvARB},
	// {"glVertexAttrib4ubvNV", &VertexAttrib4ubvNV},
	// {"glVertexAttrib4uiv", &VertexAttrib4uiv},
	// {"glVertexAttrib4uivARB", &VertexAttrib4uivARB},
	// {"glVertexAttrib4usv", &VertexAttrib4usv},
	// {"glVertexAttrib4usvARB", &VertexAttrib4usvARB},
	// {"glVertexAttribDivisor", &VertexAttribDivisor},
	// {"glVertexAttribDivisorARB", &VertexAttribDivisorARB},
	// {"glVertexAttribI1i", &VertexAttribI1i},
	// {"glVertexAttribI1iEXT", &VertexAttribI1iEXT},
	// {"glVertexAttribI1iv", &VertexAttribI1iv},
	// {"glVertexAttribI1ivEXT", &VertexAttribI1ivEXT},
	// {"glVertexAttribI1ui", &VertexAttribI1ui},
	// {"glVertexAttribI1uiEXT", &VertexAttribI1uiEXT},
	// {"glVertexAttribI1uiv", &VertexAttribI1uiv},
	// {"glVertexAttribI1uivEXT", &VertexAttribI1uivEXT},
	// {"glVertexAttribI2i", &VertexAttribI2i},
	// {"glVertexAttribI2iEXT", &VertexAttribI2iEXT},
	// {"glVertexAttribI2iv", &VertexAttribI2iv},
	// {"glVertexAttribI2ivEXT", &VertexAttribI2ivEXT},
	// {"glVertexAttribI2ui", &VertexAttribI2ui},
	// {"glVertexAttribI2uiEXT", &VertexAttribI2uiEXT},
	// {"glVertexAttribI2uiv", &VertexAttribI2uiv},
	// {"glVertexAttribI2uivEXT", &VertexAttribI2uivEXT},
	// {"glVertexAttribI3i", &VertexAttribI3i},
	// {"glVertexAttribI3iEXT", &VertexAttribI3iEXT},
	// {"glVertexAttribI3iv", &VertexAttribI3iv},
	// {"glVertexAttribI3ivEXT", &VertexAttribI3ivEXT},
	// {"glVertexAttribI3ui", &VertexAttribI3ui},
	// {"glVertexAttribI3uiEXT", &VertexAttribI3uiEXT},
	// {"glVertexAttribI3uiv", &VertexAttribI3uiv},
	// {"glVertexAttribI3uivEXT", &VertexAttribI3uivEXT},
	// {"glVertexAttribI4bv", &VertexAttribI4bv},
	// {"glVertexAttribI4bvEXT", &VertexAttribI4bvEXT},
	// {"glVertexAttribI4i", &VertexAttribI4i},
	// {"glVertexAttribI4iEXT", &VertexAttribI4iEXT},
	// {"glVertexAttribI4iv", &VertexAttribI4iv},
	// {"glVertexAttribI4ivEXT", &VertexAttribI4ivEXT},
	// {"glVertexAttribI4sv", &VertexAttribI4sv},
	// {"glVertexAttribI4svEXT", &VertexAttribI4svEXT},
	// {"glVertexAttribI4ubv", &VertexAttribI4ubv},
	// {"glVertexAttribI4ubvEXT", &VertexAttribI4ubvEXT},
	// {"glVertexAttribI4ui", &VertexAttribI4ui},
	// {"glVertexAttribI4uiEXT", &VertexAttribI4uiEXT},
	// {"glVertexAttribI4uiv", &VertexAttribI4uiv},
	// {"glVertexAttribI4uivEXT", &VertexAttribI4uivEXT},
	// {"glVertexAttribI4usv", &VertexAttribI4usv},
	// {"glVertexAttribI4usvEXT", &VertexAttribI4usvEXT},
	// {"glVertexAttribIPointer", &VertexAttribIPointer},
	// {"glVertexAttribIPointerEXT", &VertexAttribIPointerEXT},
	// {"glVertexAttribP1ui", &VertexAttribP1ui},
	// {"glVertexAttribP1uiv", &VertexAttribP1uiv},
	// {"glVertexAttribP2ui", &VertexAttribP2ui},
	// {"glVertexAttribP2uiv", &VertexAttribP2uiv},
	// {"glVertexAttribP3ui", &VertexAttribP3ui},
	// {"glVertexAttribP3uiv", &VertexAttribP3uiv},
	// {"glVertexAttribP4ui", &VertexAttribP4ui},
	// {"glVertexAttribP4uiv", &VertexAttribP4uiv},
	// {"glVertexAttribPointer", &VertexAttribPointer},
	// {"glVertexAttribPointerARB", &VertexAttribPointerARB},
	// {"glVertexAttribPointerNV", &VertexAttribPointerNV},
	// {"glVertexAttribs1dvNV", &VertexAttribs1dvNV},
	// {"glVertexAttribs1fvNV", &VertexAttribs1fvNV},
	// {"glVertexAttribs1svNV", &VertexAttribs1svNV},
	// {"glVertexAttribs2dvNV", &VertexAttribs2dvNV},
	// {"glVertexAttribs2fvNV", &VertexAttribs2fvNV},
	// {"glVertexAttribs2svNV", &VertexAttribs2svNV},
	// {"glVertexAttribs3dvNV", &VertexAttribs3dvNV},
	// {"glVertexAttribs3fvNV", &VertexAttribs3fvNV},
	// {"glVertexAttribs3svNV", &VertexAttribs3svNV},
	// {"glVertexAttribs4dvNV", &VertexAttribs4dvNV},
	// {"glVertexAttribs4fvNV", &VertexAttribs4fvNV},
	// {"glVertexAttribs4svNV", &VertexAttribs4svNV},
	// {"glVertexAttribs4ubvNV", &VertexAttribs4ubvNV},
	// {"glVertexP2ui", &VertexP2ui},
	// {"glVertexP2uiv", &VertexP2uiv},
	// {"glVertexP3ui", &VertexP3ui},
	// {"glVertexP3uiv", &VertexP3uiv},
	// {"glVertexP4ui", &VertexP4ui},
	// {"glVertexP4uiv", &VertexP4uiv},
	{"glVertexPointer", &VertexPointer},
	// {"glVertexPointerEXT", &VertexPointerEXT},
	{"glViewport", &Viewport},
	// {"glWaitSync", &WaitSync},
	// {"glWindowPos2d", &WindowPos2d},
	// {"glWindowPos2dARB", &WindowPos2dARB},
	// {"glWindowPos2dMESA", &WindowPos2dMESA},
	// {"glWindowPos2dv", &WindowPos2dv},
	// {"glWindowPos2dvARB", &WindowPos2dvARB},
	// {"glWindowPos2dvMESA", &WindowPos2dvMESA},
	// {"glWindowPos2f", &WindowPos2f},
	// {"glWindowPos2fARB", &WindowPos2fARB},
	// {"glWindowPos2fMESA", &WindowPos2fMESA},
	// {"glWindowPos2fv", &WindowPos2fv},
	// {"glWindowPos2fvARB", &WindowPos2fvARB},
	// {"glWindowPos2fvMESA", &WindowPos2fvMESA},
	// {"glWindowPos2i", &WindowPos2i},
	// {"glWindowPos2iARB", &WindowPos2iARB},
	// {"glWindowPos2iMESA", &WindowPos2iMESA},
	// {"glWindowPos2iv", &WindowPos2iv},
	// {"glWindowPos2ivARB", &WindowPos2ivARB},
	// {"glWindowPos2ivMESA", &WindowPos2ivMESA},
	// {"glWindowPos2s", &WindowPos2s},
	// {"glWindowPos2sARB", &WindowPos2sARB},
	// {"glWindowPos2sMESA", &WindowPos2sMESA},
	// {"glWindowPos2sv", &WindowPos2sv},
	// {"glWindowPos2svARB", &WindowPos2svARB},
	// {"glWindowPos2svMESA", &WindowPos2svMESA},
	// {"glWindowPos3d", &WindowPos3d},
	// {"glWindowPos3dARB", &WindowPos3dARB},
	// {"glWindowPos3dMESA", &WindowPos3dMESA},
	// {"glWindowPos3dv", &WindowPos3dv},
	// {"glWindowPos3dvARB", &WindowPos3dvARB},
	// {"glWindowPos3dvMESA", &WindowPos3dvMESA},
	// {"glWindowPos3f", &WindowPos3f},
	// {"glWindowPos3fARB", &WindowPos3fARB},
	// {"glWindowPos3fMESA", &WindowPos3fMESA},
	// {"glWindowPos3fv", &WindowPos3fv},
	// {"glWindowPos3fvARB", &WindowPos3fvARB},
	// {"glWindowPos3fvMESA", &WindowPos3fvMESA},
	// {"glWindowPos3i", &WindowPos3i},
	// {"glWindowPos3iARB", &WindowPos3iARB},
	// {"glWindowPos3iMESA", &WindowPos3iMESA},
	// {"glWindowPos3iv", &WindowPos3iv},
	// {"glWindowPos3ivARB", &WindowPos3ivARB},
	// {"glWindowPos3ivMESA", &WindowPos3ivMESA},
	// {"glWindowPos3s", &WindowPos3s},
	// {"glWindowPos3sARB", &WindowPos3sARB},
	// {"glWindowPos3sMESA", &WindowPos3sMESA},
	// {"glWindowPos3sv", &WindowPos3sv},
	// {"glWindowPos3svARB", &WindowPos3svARB},
	// {"glWindowPos3svMESA", &WindowPos3svMESA},
	// {"glWindowPos4dMESA", &WindowPos4dMESA},
	// {"glWindowPos4dvMESA", &WindowPos4dvMESA},
	// {"glWindowPos4fMESA", &WindowPos4fMESA},
	// {"glWindowPos4fvMESA", &WindowPos4fvMESA},
	// {"glWindowPos4iMESA", &WindowPos4iMESA},
	// {"glWindowPos4ivMESA", &WindowPos4ivMESA},
	// {"glWindowPos4sMESA", &WindowPos4sMESA},
	// {"glWindowPos4svMESA", &WindowPos4svMESA},
	// {"glXChooseFBConfig", &XChooseFBConfig},
	// {"glXChooseFBConfigSGIX", &XChooseFBConfigSGIX},
	// {"glXChooseVisual", &XChooseVisual},
	// {"glXCopyContext", &XCopyContext},
	// {"glXCreateContext", &XCreateContext},
	// {"glXCreateContextWithConfigSGIX", &XCreateContextWithConfigSGIX},
	// {"glXCreateGLXPbufferSGIX", &XCreateGLXPbufferSGIX},
	// {"glXCreateGLXPixmap", &XCreateGLXPixmap},
	// {"glXCreateGLXPixmapMESA", &XCreateGLXPixmapMESA},
	// {"glXCreateGLXPixmapWithConfigSGIX", &XCreateGLXPixmapWithConfigSGIX},
	// {"glXCreateNewContext", &XCreateNewContext},
	// {"glXCreatePbuffer", &XCreatePbuffer},
	// {"glXCreatePixmap", &XCreatePixmap},
	// {"glXCreateWindow", &XCreateWindow},
	// {"glXDestroyContext", &XDestroyContext},
	// {"glXDestroyGLXPbufferSGIX", &XDestroyGLXPbufferSGIX},
	// {"glXDestroyGLXPixmap", &XDestroyGLXPixmap},
	// {"glXDestroyPbuffer", &XDestroyPbuffer},
	// {"glXDestroyPixmap", &XDestroyPixmap},
	// {"glXDestroyWindow", &XDestroyWindow},
	// {"glXFreeContextEXT", &XFreeContextEXT},
	// {"glXGetClientString", &XGetClientString},
	// {"glXGetConfig", &XGetConfig},
	// {"glXGetContextIDEXT", &XGetContextIDEXT},
	// {"glXGetCurrentContext", &XGetCurrentContext},
	// {"glXGetCurrentDisplay", &XGetCurrentDisplay},
	// {"glXGetCurrentDisplayEXT", &XGetCurrentDisplayEXT},
	// {"glXGetCurrentDrawable", &XGetCurrentDrawable},
	// {"glXGetCurrentReadDrawable", &XGetCurrentReadDrawable},
	// {"glXGetDriverConfig", &XGetDriverConfig},
	// {"glXGetFBConfigAttrib", &XGetFBConfigAttrib},
	// {"glXGetFBConfigAttribSGIX", &XGetFBConfigAttribSGIX},
	// {"glXGetFBConfigFromVisualSGIX", &XGetFBConfigFromVisualSGIX},
	// {"glXGetFBConfigs", &XGetFBConfigs},
	// {"glXGetProcAddress", &XGetProcAddress},
	// {"glXGetProcAddressARB", &XGetProcAddressARB},
	// {"glXGetScreenDriver", &XGetScreenDriver},
	// {"glXGetSelectedEvent", &XGetSelectedEvent},
	// {"glXGetSelectedEventSGIX", &XGetSelectedEventSGIX},
	// {"glXGetVisualFromFBConfig", &XGetVisualFromFBConfig},
	// {"glXGetVisualFromFBConfigSGIX", &XGetVisualFromFBConfigSGIX},
	// {"glXImportContextEXT", &XImportContextEXT},
	// {"glXIsDirect", &XIsDirect},
	// {"glXMakeContextCurrent", &XMakeContextCurrent},
	// {"glXMakeCurrent", &XMakeCurrent},
	// {"glXMakeCurrentReadSGI", &XMakeCurrentReadSGI},
	// {"glXQueryContext", &XQueryContext},
	// {"glXQueryContextInfoEXT", &XQueryContextInfoEXT},
	// {"glXQueryDrawable", &XQueryDrawable},
	// {"glXQueryExtension", &XQueryExtension},
	// {"glXQueryExtensionsString", &XQueryExtensionsString},
	// {"glXQueryGLXPbufferSGIX", &XQueryGLXPbufferSGIX},
	// {"glXQueryServerString", &XQueryServerString},
	// {"glXQueryVersion", &XQueryVersion},
	// {"glXSelectEvent", &XSelectEvent},
	// {"glXSelectEventSGIX", &XSelectEventSGIX},
	// {"glXSwapBuffers", &XSwapBuffers},
	// {"glXUseXFont", &XUseXFont},
	// {"glXWaitGL", &XWaitGL},
	// {"glXWaitX", &XWaitX},

	// "wglChoosePixelFormat",
	// "wglCopyContext",
	// "wglCreateContext",
	// "wglCreateLayerContext",
	// "wglDeleteContext",
	// "wglDescribeLayerPlane",
	// "wglDescribePixelFormat",
	// "wglGetCurrentContext",
	// "wglGetCurrentDC",
	// "wglGetDefaultProcAddress",
	// "wglGetLayerPaletteEntries",
	// "wglGetPixelFormat",
	// "wglGetProcAddress",
	// "wglMakeCurrent",
	// "wglRealizeLayerPalette",
	// "wglSetLayerPaletteEntries",
	// "wglSetPixelFormat",
	// "wglShareLists",
	// "wglSwapBuffers",
	// "wglSwapLayerBuffers",
	// "wglSwapMultipleBuffers",
	// "wglUseFontBitmapsA",
	// "wglUseFontBitmapsW",
	// "wglUseFontOutlinesA",
	// "wglUseFontOutlinesW",
}
